# Task 1: Data Type Objects in NumPy
1. Create a NumPy array using np.array() function and specify the data type as 'int32.' Print the array and its data type.

2. Create another NumPy array using np.array() with the data type as 'float64.' Print the array and its data type.

In [3]:
import numpy as np

array1 = [2, 4, 4, 7, 8]
array2 = [1.3, 2.4, 4.2, 5.5]


np_array1 = np.array(array1)
np_array2 = np.array(array2)

shape1 = np_array1.shape
shape2 = np_array2.shape

size1 = np_array1.size 
size2 = np_array2.size

datatype1 = np_array1.dtype
datatype2 = np_array2.dtype

print("Array 1")
print("Array:", array1)
print("Shape of Array 1:", shape1)
print("Size of Array 1:", size1)
print("Datatype of Array 1:", datatype1)

print("\nArray 2")
print("Array:", array2)
print("Shape of Array 2:", shape2)
print("Size of Array 2:", size2)
print("Datatype of Array 2:", datatype2)

Array 1
Array: [2, 4, 4, 7, 8]
Shape of Array 1: (5,)
Size of Array 1: 5
Datatype of Array 1: int64

Array 2
Array: [1.3, 2.4, 4.2, 5.5]
Shape of Array 2: (4,)
Size of Array 2: 4
Datatype of Array 2: float64


# Task 2: One-Dimensional and Multidimensional Arrays
1. Create a one-dimensional NumPy array containing the integers from 1 to 5. Print the array.

2. Create a two-dimensional NumPy array (matrix) with the following values:

In [10]:
import numpy as np

# One-dimensional array containing integers from 1 to 5
one_d_array = np.array([1, 2, 3, 4, 5])
print("One-dimensional array:")
print(one_d_array)

# Two-dimensional array (matrix)
two_d_array = np.array([[1, 2, 3],
                        [4, 5, 6]])
print("\nTwo-dimensional array:")
print(two_d_array)

One-dimensional array:
[1 2 3 4 5]

Two-dimensional array:
[[1 2 3]
 [4 5 6]]


# Task 3: NumPy Operations

1. Create two NumPy arrays arr1 and arr2 with any values of your choice. Perform element-wise addition, subtraction, multiplication, and division between these arrays and print the results.

2. Calculate the dot product between arr1 and arr2. Print the result.

3. Use NumPy to calculate the mean, median, and standard deviation of arr1.

In [ ]:
import numpy as np
# Creating two arrays with chosen values
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

# Element-wise operations
print("\nElement-wise Addition:")
print(arr1 + arr2)

print("\nElement-wise Subtraction:")
print(arr1 - arr2)

print("\nElement-wise Multiplication:")
print(arr1 * arr2)

print("\nElement-wise Division:")
print(arr1 / arr2)

# Dot product
dot_product = np.dot(arr1, arr2)
print("\nDot Product of arr1 and arr2:")
print(dot_product)

# Statistics on arr1
mean_val = np.mean(arr1)
median_val = np.median(arr1)
std_dev = np.std(arr1)

print("\nStatistics for arr1:")
print(f"Mean: {mean_val}")
print(f"Median: {median_val}")
print(f"Standard Deviation: {std_dev}")


Element-wise Addition:
[11 22 33]

Element-wise Subtraction:
[ 9 18 27]

Element-wise Multiplication:
[10 40 90]

Element-wise Division:
[10. 10. 10.]

Dot Product of arr1 and arr2:
140

Statistics for arr1:
Mean: 20.0
Median: 20.0
Standard Deviation: 8.16496580927726
1
